---
title: "Lecture 13: A brief introduction to Python"
subtitle: "Intro to Data Science for Public Policy, Spring 2016"
author: "by Jeff Chen & Dan Hammer, Georgetown University McCourt School of Public Policy"
output: 
  html_document: 
    theme: journal
    toc: yes
---


The concepts that we have learned during this course are, for the most part,
independent of `R`.  

The hardest part of learning a new programming language for data science is
getting your environment set up. We have chosen [Jupyter](http://jupyter.org/)
as the environment, since it is quick to set up and amazingly useful in data-
driven research and reports.

[Review the relative merits of Python and R for data science.](https://www.datacamp.com/community/tutorials/r-or-python-for-data-analysis)

### Try it out

You can try out Jupyter online, without installing anything.  Go to [try.jupyter.org](https://try.jupyter.org/) and click the **Welcome to R - demo** notebook.  Click the first cell, with only text.  Add a couple of lines.  Click the keyboard icon at the top to see the available keyboard shortcuts.  Execute the cell and move to the next cell -- one with code.  Add a line you *know* works.  Execute the cell.

Now, go back to [try.jupyter.org](https://try.jupyter.org/).  Open the **Welcome to Python** notebook.  Click the plus sign icon in the toolbar to generate a new code cell.  Type the following line and execute the cell.

```python
print("yes")
```

You should see the `yes` printed below.  The l If you are unable or unwilling to install Jupyter locally, you can execute many of the commands in this lecture from the browser.  You will not be able, and you may need to contend with poor or spotty connections to the trial servers.

### Installation

In order to follow along with this lecture, you will need to [install Jupyter](http://jupyter.readthedocs.io/en/latest/install.html).   I highly recommend that you install Jupyter using [Anaconda](https://www.continuum.io/downloads), rather than the more advanced install mentioned in the docs.  I have reproduced the basic steps for installation below, but please refer to the official installation for more details.

1. Download [Anaconda](https://www.continuum.io/downloads). We recommend downloading Anaconda’s latest Python 3 version (currently Python 3.5).

2. Install the version of Anaconda which you downloaded, following the instructions on the download page.

3. Run the notebook by typing `jupyter notebook` into your command line.  Refer to [this page](http://jupyter.readthedocs.io/en/latest/running.html#running) on running the notebook for more details.

If you have any trouble with installation, please contact Jeff or Dan.  

### Create a notebook

First, we'll create a notebook from scratch, just to demonstrate some of the features.  Then we will work on answering questions embedded in an existing notebook.  

- Launch a new **Python** notebook from the dropdown **New** button (depending on your install).  Click the title and rename the notebook **Example**.  
- We will write an illustrative notebook of a [Damped sine wave](https://en.wikipedia.org/wiki/Damped_sine_wave).  This isn't just an academic exercise.  Jupyter Notebooks have been used to illustrate game-changing research -- and allow users to easily reproduce the findings.  Consider, for example, this article in the New York Times, [*Gravitational Waves Detected, Confirming Einstein’s Theory*](https://www.nytimes.com/2016/02/12/science/ligo-gravitational-waves-black-holes-einstein.html).  [Here is the binder](http://mybinder.org/repo/minrk/ligo-binder/notebooks/GW150914_tutorial.ipynb) for [the notebook](https://github.com/minrk/ligo-binder/blob/master/GW150914_tutorial.ipynb) to reproduce the findings.  (A Binder provides a backend for a notebook to run exclusively in the browser -- and developed by my college roommate!)
- Copy the following text into a markdown cell.  Note the use of LaTeX that is automatically rendered.

	```text
	A damped sine wave is a sinusoidal function whose amplitude approaches zero as
	time increases.  Damped sine waves are commonly seen in science and
	engineering, wherever a harmonic oscillator is losing energy faster than it is
	being supplied.  An example of a damped sine wave is:

	$$
	f(t) = e^{-t} \cdot cos(2 \pi t)
	$$
```

- Then copy this code into a new, code cell and execute to see the embedded graph.  

	```python
	import numpy as np
	import matplotlib.pyplot as plt

	def f(t):
	    return np.exp(-t) * np.sin(2*np.pi*t)

	t1 = np.arange(0.0, 5.0, 0.1)
	t2 = np.arange(0.0, 5.0, 0.02)

	plt.figure(1)
	plt.subplot(211)
	plt.plot(t1, f(t1), 'bo', t2, f(t2), 'k')

	plt.subplot(212)
	plt.plot(t2, np.sin(2*np.pi*t2), 'r--')
	plt.show()
	```

Save the notebook for later use.  This is, admittedly, a more complex Python code snippet, but it's not too bad relative to the code we've worked on in this class.  You can immediately start to engage with the code and share the results with Jupyter.

### Learn Python and do something useful

Now open [`lecture13.ipynb`]().  Follow along in class and try to execute the required code snippets.  Full disclosure: you are helping do my homework.  I need to understand how many earth observing satellites are currently active.  Thanks for the help!










